{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
rules:
  - apiGroups: ["phoenix.io"]
    resources:
      - kubeapplications
      - kubeapplications/status
      - kubeapplications/finalizers
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
{{- end }}
